spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dongnae  # 사용할 데이터베이스 이름으로 변경
    username: root                              # MySQL 사용자 이름
    password: 1234                              # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver          # MySQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true                                       # SQL 쿼리 로그 출력 여부
    properties:
      hibernate:
        format_sql: true                                 # SQL 쿼리 포맷 설정
        dialect: org.hibernate.dialect.MySQLDialect

